const dogs = [
  {
    id: 'dog1',
    imageUrl: 'https://fortunedotcom.files.wordpress.com/2019/01/boo.jpg',
    name: 'Ralph',
    disposition: 'prissy',
    faveTreat: 'carrot sticks',
    isPettable: true,
    furType: 'fluffy',
  },
  {
    id: 'dog2',
    imageUrl: 'https://d17fnq9dkz9hgj.cloudfront.net/uploads/2018/04/Bulldog_02.jpg',
    name: 'Snowball',
    disposition: 'sweet',
    faveTreat: 'rawhide',
    isPettable: true,
    furType: 'scruffy',
  },
  {
    id: 'dog3',
    imageUrl: 'https://imgix.ranker.com/user_node_img/50044/1000864402/original/1-photo-u1?w=650&q=50&fm=pjpg&fit=crop&crop=faces',
    name: 'Lucky',
    disposition: 'feisty',
    faveTreat: 'ice cream',
    isPettable: true,
    furType: 'sleek',
  },
  {
    id: 'dog4',
    imageUrl: 'https://d17fnq9dkz9hgj.cloudfront.net/uploads/2018/04/Beagle_02.jpg',
    name: 'Bullseye',
    disposition: 'shy',
    faveTreat: 'dentastix',
    isPettable: false,
    furType: 'wiry',
  },
  {
    id: 'dog5',
    imageUrl: 'https://i0.wp.com/metro.co.uk/wp-content/uploads/2018/12/SEI_44690013-fec1.jpg?quality=90&strip=all&zoom=1&resize=644%2C483&ssl=1',
    name: 'Beethoven',
    disposition: 'flirty',
    faveTreat: 'cookies',
    isPettable: true,
    furType: 'fluffy',
  },
  {
    id: 'dog6',
    imageUrl: 'https://i0.wp.com/metro.co.uk/wp-content/uploads/2018/12/SEI_44690013-fec1.jpg?quality=90&strip=all&zoom=1&resize=644%2C483&ssl=1',
    name: 'Beethoven',
    disposition: 'flirty',
    faveTreat: 'cookies',
    isPettable: true,
    furType: 'fluffy',
  },
  {
    id: 'dog7',
    imageUrl: 'https://i0.wp.com/metro.co.uk/wp-content/uploads/2018/12/SEI_44690013-fec1.jpg?quality=90&strip=all&zoom=1&resize=644%2C483&ssl=1',
    name: 'Beethoven',
    disposition: 'flirty',
    faveTreat: 'cookies',
    isPettable: true,
    furType: 'fluffy',
  },
  {
    id: 'dog8',
    imageUrl: 'https://i0.wp.com/metro.co.uk/wp-content/uploads/2018/12/SEI_44690013-fec1.jpg?quality=90&strip=all&zoom=1&resize=644%2C483&ssl=1',
    name: 'Beethoven',
    disposition: 'flirty',
    faveTreat: 'cookies',
    isPettable: true,
    furType: 'fluffy',
  },
];

export default dogs;
